apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-apps
  labels:
    app: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: res-api
          image: tundaey/tripvat_rest-api
          ports:
            - containerPort: 80