FROM node:12-alpine
RUN apk --no-cache --virtual build-dependencies add make python g++
COPY . /opt/app

WORKDIR /opt/app

# RUN npm install
# RUN apk --no-cache --virtual build-dependencies add make python g++
# RUN npm install
RUN npm install --no-optional && npm cache clean --force
# RUN apk del build-dependencies

RUN ls

CMD npm run dev